const express = require("express");
const cors = require("cors");
const PORT = process.env.PORT || 3004;
//  const userRoute = require("./routes/user");
// const roleRouter = require("./routes/role");
const app = express();
app.use(cors());
app.use(express.json());
// app.use("/", userRoute);
// app.use("/", roleRouter);
app.listen(PORT, () => console.log(`Listening on port: ${PORT}`));
